### PR TITLE
Added functions to wrap SDL_PollEvent()

### PR DESCRIPTION
**Pull request by Vraiment**
As I mentioned in issue #51 it would be a good idea to decouple event polling and event handling. These commits contain functions to wrap _SDL\_PollEvent()_ where may pass a custom event handler that might be either a normal function, a lambda or a struct/class instance that has an _operator()(SDL_Event)_ member function, example:

```
bool quit = false;
auto eventHandler = [&quit](const SDL_Event& event) { 
    quit = (event.type == SDL_QUIT);
};

while (!quit) {
    SDL2pp::PollAllEvents(eventHandler);

    // ...
}
```

This does not solve the issue with the actual event handling (the horrible switch) but is the first step to simplify the event subsystem.

Also, as mentioned in pull request #104 I wanted to start using Catch in these changes. I missed your last update and I went ahead and wrote the tests with Catch. If you still prefer to use _testing.h_ I can go ahead an update the tests, it shouldn't be difficult. I want to note that using Catch fixes the issue with XCode showing the colored output while still displaying it on terminal without any extra configuration.

### CODE REVIEW

**Comment by Vraiment** [comment]
Well this is embarrassing, I don't know what the issue is for the windows failed build but from the logs I see it has to do with Catch, probably it just needs set a configuration switch...

I cannot get cmake to work in my windows machine, so I will take a look at it later if you could take a look at the rest I would be grateful

**Comment by Vraiment** [comment]
I removed Catch to see if that was the issue, good news is not Catch (that mean's there should be no issue switching to catch), bad news is that the changes are the ones with issues maybe is using SLD2PP_EXPORT on free templated functions will investigate it.

**Comment by Vraiment** [comment]
It seems I misread the output, the issue was exporting templated functions, so I put Catch back again

**Comment by AMDmi3** [comment]
A nice idea to separate this from handler class. It is still desired though. Also:

- this should be separate from catch import. Switch to Catch can go in parallel, while this could be developed without tests for now.
- what are non-template functions which just ignore events for?
- I forgot to mention an another idea: we could use similar functions which call SDL_WaitEvent and SDL_WaitEventTimeout (wrapped by a single function with ```Optional<>``` argument).
- I'd put the functions into a dedicated namespace, e.g.

```
namespace SDL2pp {
    namespace Events {
        template <class T>
        bool Poll(T&& handler);

        template <class T>
        bool PollAll(T&& handler);

        template <class T>
        bool Wait(T&& handler, Optional<int> timeout = Optional<int>());
    }
}
```

- note &&, it allows to define handling lambda inplace

**Comment by Vraiment** [comment]
Catch removed, added perfect forwarding to the templates.

Creating a wrapper for SDL_WaitEvent sounds like a good idea but I won't be making it on this PR, right now I don't have time, but will do it, we can merge these changes as a stand alone.

Finally, for the ignore events functions I imagine that sometimes you might want to remove an event or just empty the event queue. Certainly is not the most common usage but sounds nice to be able to just call `PollAllEvents();` rather than `PullAllEvents([](SDL_Event&) { });`.

**Comment by Vraiment** [comment]
Managed to find some time for the SDL_WaitEvent wrappers

**Comment by Vraiment** [comment]
I'm working on a better wrapper for EventPolling, is not ready yet

**Pull request closed without merging**
